module 3 complete
js-tasks-ru/jsbasic-20240321_aventus pull request #12
Opened 2024-04-05 20:41 UTC by AkiraNewzoo

2024-04-05 20:42 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-04-06 15:19 UTC, SinimaWath requested changes

2024-04-06 15:19 UTC, SinimaWath commented on 3-module/1-task/index.js
> +let names = namify(users);
Из файла с задачей, нужно убрать весь лишний код, кроме функции с решением

2024-04-06 15:19 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  });
Давай тут использовать: `users.map`

2024-04-06 15:19 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  });
Давай тут использовать: `arr.filter(...).map(...)`

2024-04-06 15:19 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  }
Давай тут используем: `str.split('-').map((value, index) => ....).join('')`

2024-04-06 15:19 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  }
Вместо for of, давай используем: `map`

2024-04-08 16:39 UTC, closed without merging